export const VARIABLES = {
  MAIN_MAP_WIDTH     : 1440,
  MAIN_MAP_HEIGHT    : 1017,
  MAIN_MAP_CELL_SIZE : 5,

  MAX_MULTY_PRODUCT_IN_TOWN     : 2,
  MAX_COMPLEX_PRODUCT_IN_TOWN   : 3,
  MAX_COMPLEX_AND_MULTY_IN_TOWN : 4,
  MAX_PRODUCTS_IN_TOWN          : 5
}
